"""Turn a Model into the tab-separated scene file Sh3dWriter reads.

Why a second format rather than reading JSON in Java: the writer has to run on
Sweet Home 3D's own classes, and dragging a JSON library onto that classpath
buys nothing. A tab-separated line format parses with split() and cannot fail in
an interesting way.

Two corrections are applied here, in one place, rather than being scattered:

1. **Y is flipped.** DXF has Y increasing upward; Sweet Home 3D's plan has Y
   increasing downward. Without the flip every plan comes out mirrored, which is
   the kind of error that looks plausible until a door is on the wrong side.

2. **Coordinates are re-origined** so the model starts near (0, 0). Polycam
   sheet coordinates are fine but arbitrary, and keeping them would leave the
   model floating away from Sweet Home 3D's origin.

Both corrections are computed from the bounds of the *whole* model and applied
to walls, rooms and lights alike. Transforming only the geometry and forgetting
the lights would put every fitting in a mirrored position -- lit rooms, wrong
rooms.

TEXTURE FALLBACK LIVES HERE. Sh3dWriter does not guess: it applies exactly the
texture id it is given. Deciding that a wall the scan missed should fall back to
the generic tiled patch needs to know which walls were covered, which is what
this module has and Java does not.

Format written (see Sh3dWriter's header for the authoritative description):

    home     <name>   <wallHeight>
    texture  <id>     <absolutePath>  <widthCm>  <heightCm>
    level    <id>     <name>  <elevation>  <floorThickness>  <height>
    wall     <level>  <xStart> <yStart> <xEnd> <yEnd> <thickness> <height> [leftTex] [rightTex]
    room     <level>  <name>   <floorTex> <ceilTex> <x,y> <x,y> ...
    light    <level>  <name>   <x> <y> <elevation> <power>
"""

from __future__ import annotations

from pathlib import Path

from .schema import Light, Model, WallTexture

FLOOR_THICKNESS_CM = 12.0
DEFAULT_WALL_HEIGHT_CM = 250.0
NONE = "-"


def level_id(index: int) -> str:
    """Scene-file id for a level. Sh3dWriter keys levels by this string."""
    return f"l{index}"


def _fmt(value: float) -> str:
    """Three decimals is well under a millimetre in centimetres; drop the noise."""
    return f"{round(value, 3):g}"


def write_scene(
    model: Model,
    out: str | Path,
    *,
    wall_textures: list[WallTexture] | None = None,
    tiled_textures: dict[str, Path] | None = None,
    lights: list[Light] | None = None,
    tile_cm: float = 100.0,
    home_name: str | None = None,
    elevation_overrides: dict[str, float] | None = None,
    floor_thickness_cm: float = FLOOR_THICKNESS_CM,
    include_ceilings: bool = False,
) -> dict:
    """Write `model` as a scene file. Returns a summary for the caller to report.

    `include_ceilings` is off by default and that is deliberate: a room with a
    visible ceiling occludes itself when the plugin renders that level from
    above, so a ceiling texture is only worth emitting for a model being viewed
    some other way.
    """
    out = Path(out)
    wall_textures = wall_textures or []
    tiled = dict(tiled_textures or {})
    lights = lights or []
    overrides = elevation_overrides or {}

    min_x, _min_y, _max_x, max_y = model.bounds()

    def fx(x: float) -> str:
        return _fmt(x - min_x)

    def fy(y: float) -> str:
        # Flip Y (DXF up -> Sweet Home 3D down) and re-origin in one step.
        return _fmt(max_y - y)

    lines: list[str] = [
        f"# generated by scan2ha from {model.source}",
        "# units are centimetres; see Sh3dWriter.java for the record format",
    ]

    name = home_name or Path(model.source).stem or "scan2ha"
    wall_height = _default_wall_height(model)
    lines.append(f"home\t{name}\t{_fmt(wall_height)}")

    # --- textures, first, so every id is registered before it is referenced ---
    by_wall = {(entry.level, entry.wall): entry for entry in wall_textures}

    for kind in ("floor", "wall", "ceiling"):
        if kind == "ceiling" and not include_ceilings:
            continue
        path = tiled.get(kind)
        if path is not None:
            lines.append(
                f"texture\t{kind}\t{Path(path).resolve()}\t{_fmt(tile_cm)}\t{_fmt(tile_cm)}"
            )

    for li, level in enumerate(model.levels):
        for wi, wall in enumerate(level.walls):
            entry = by_wall.get((li, wi))
            if entry is None:
                continue
            for side in ("left", "right"):
                image = getattr(entry, side)
                if image is None:
                    continue
                # Sized to the wall itself, so the rectified photo covers it
                # once instead of tiling into wallpaper.
                lines.append(
                    f"texture\t{_wall_texture_id(li, wi, side)}\t{Path(image).resolve()}"
                    f"\t{_fmt(wall.length_cm)}\t{_fmt(wall.height)}"
                )

    # --- levels, all of them, before any geometry references one ---
    for li, level in enumerate(model.levels):
        elevation = overrides.get(level.name, level.elevation_cm)
        if elevation is None:
            elevation = 0.0
        lines.append(
            f"level\t{level_id(li)}\t{level.name}\t{_fmt(elevation)}"
            f"\t{_fmt(floor_thickness_cm)}\t{_fmt(level.ceiling_height_cm)}"
        )

    # --- geometry ---
    floor_tex = "floor" if "floor" in tiled else NONE
    ceiling_tex = "ceiling" if (include_ceilings and "ceiling" in tiled) else NONE
    generic_wall = "wall" if "wall" in tiled else NONE

    for li, level in enumerate(model.levels):
        lid = level_id(li)
        for wi, wall in enumerate(level.walls):
            entry = by_wall.get((li, wi))
            sides = []
            for side in ("left", "right"):
                image = getattr(entry, side, None) if entry else None
                sides.append(_wall_texture_id(li, wi, side) if image else generic_wall)
            lines.append(
                f"wall\t{lid}\t{fx(wall.x_start)}\t{fy(wall.y_start)}"
                f"\t{fx(wall.x_end)}\t{fy(wall.y_end)}"
                f"\t{_fmt(wall.thickness)}\t{_fmt(wall.height)}"
                f"\t{sides[0]}\t{sides[1]}"
            )
        for room in level.rooms:
            pts = "\t".join(f"{fx(x)},{fy(y)}" for x, y in room.points)
            lines.append(
                f"room\t{lid}\t{room.name or level.name}\t{floor_tex}\t{ceiling_tex}\t{pts}"
            )

    for light in lights:
        lines.append(
            f"light\t{level_id(light.level)}\t{light.entity_id}"
            f"\t{fx(light.x)}\t{fy(light.y)}"
            f"\t{_fmt(light.elevation)}\t{_fmt(light.power)}"
        )

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")

    return {
        "path": out,
        "levels": len(model.levels),
        "walls": sum(len(lv.walls) for lv in model.levels),
        "rooms": sum(len(lv.rooms) for lv in model.levels),
        "lights": len(lights),
        "textured_walls": len(by_wall),
        "unknown_elevations": [
            lv.name
            for lv in model.levels
            if lv.name not in overrides and lv.elevation_cm is None
        ],
    }


def _wall_texture_id(level: int, wall: int, side: str) -> str:
    return f"w{level}_{wall}_{side}"


def _default_wall_height(model: Model) -> float:
    """Home's default wall height; Sweet Home 3D takes it in the constructor."""
    for level in model.levels:
        if level.ceiling_height_cm:
            return level.ceiling_height_cm
    return DEFAULT_WALL_HEIGHT_CM
